### ISSUE TITLE
Kirby 3: "The field type "focus" does not exist"

### ISSUE THREAD

**Issue by MathiasGmeiner** [flokosiol/kirby-focus#33]
Hey, if I try to add the focus field to a blueprint like that:

```
sidebar:
  meta:
    type: fields
    fields:
      focus:
        label: My Focus Field
        type: focus
```
I get the *The field type "focus" does not exist"* error. 

 I'm on `3.0.0-beta-6.17` and dev-kit copied the folder to `site/plugins/focus` 

Am I doing something wrong?

**Comment by flokosiol** [comment]
Did you check out the `k-next` branch? The `master` branch is still for Kirby 2 only. This will change as soon as Kirby 3 is officially launched.

**Comment by MathiasGmeiner** [comment]
Yes, I'm on the `k-next` branch.
This is my folder structure: 
![bildschirmfoto 2018-11-15 um 12 41 37](https://user-images.githubusercontent.com/103595/48550756-eacf5580-e8d3-11e8-8b63-e4af81199649.png)

This is my page blueprint `member.yml`

``` 
title: Mitglied
icon: 🎟
preset: page

status:
  draft:
    label: Entwurf
    text: Die Seite ist im Entwurfsmodus und nur für eingeloggte Editoren sichtbar
  listed:
    label: Veröffentlicht
    text: Die Seite ist öffentlich für jeden

pages: false

sidebar:
  meta:
    type: fields
    fields:
      focus:
        label: My Focus Field
        type: focus

**Comment by flokosiol** [comment]
In your blueprint, you use the focus field as a field for pages, but it can only be used as a field for files. 

I'm still not 100% familiar with all the blueprint possibilities in K3, but it should work, if you change the the `type: fields` in your sidebar - meta section to `type: files`

If not, I successfully use it with this blueprint setup:

```yaml
title: Default Page

columns:
  - width: 2/3
    sections:
      content:
        type: fields
        fields:
          text:
            label: Text
            type: textarea
            size: large

  - width: 1/3
    sections:
      files:
        headline: Files
        type: files
        template: image
```

… and then in `site/blueprints/files/image.yml` (which refers to the selected template above)

```yaml
title: Image

fields:
  focus:
    label: Focus
    type: focus
```
