### ISSUE TITLE
[Question] multiple focus fields

### ISSUE THREAD

**Issue by hansgohr** [flokosiol/kirby-focus#67]
I was trying to make use of your plugin to provide "info areas" on images, with some tooltip text. However once I have multiple focus fields in the file blueprint, or they're named other than "focus" (i.e. focusA, focusB) it won't work anymore. Do you maybe have a quick solution for this or would this be something bigger? :) Thank you already!! 

i.e. like this: 

```yml
fields:
  focusPoints:
    label: FocusPoints
    type: structure
    fields:
      focus:
        label: Point
        type: focus
        width: 1/2
      text:
        label: Tooltip
        type: textarea
        width: 1/2
```
```php
<?php
    $items = $image->focusPoints()->toStructure();
    foreach ($items as $item): ?>
      <?php
        $x = $item->focusPercentageX();
        $y = $item->focusPercentageY();
       ?>
      <button style="top: <?= $y ?>%; left: <?= $x ?>%"></button>
<?php endforeach ?>
```
( I also tried it without a structure, won't work either)
